# d2 --sketch depends.d2 --watch depends.svg && open -a Arc depends.svg
app
parser
dispatcher
commandHandler
entry_repo
entry
file_adapter

app -> parser
app -> dispatcher {style.stroke-dash: 5}
app -> dataLoader
app -> UI


dataLoader -> commandHandler
dataLoader -> config {style.stroke-dash: 5}
dataLoader -> dispatcher
# :dataLoader -> entry_repo
dataLoader -> entry
dataLoader -> file_adapter

dataLoader -> entry_reader
dataLoader -> entry_writer
# entry_reader -> entry_repo {style.stroke-dash: 5}
# entry_writer -> entry_repo {style.stroke-dash: 5}
entry_reader -> file_adapter {style.stroke-dash: 5}
entry_writer -> file_adapter {style.stroke-dash: 5}
entry_reader -> entry 
entry_writer -> entry 
entry_reader -> entry_repo {style.stroke: "#ccc"}
entry_writer -> entry_repo {style.stroke: "#ccc"}
entry_repo -> entry 

dispatcher -> commandHandler {style.stroke-dash: 5}
commandHandler -> entry_reader {style.stroke-dash: 5}
commandHandler -> entry_writer {style.stroke-dash: 5}
#entry_repo -> entry    {style.stroke-dash: 5}
#entry_repo -> file_adapter {style.stroke-dash: 5}

