shape: sequence_diagram
app -> parser: parse CLI arguments ("add a note")
parser -> app: return ParsedCommand(!add, ...)
app -> dispatcher: send ParsedCommand
dispatcher -> app: return reference to Creator
app -> creator: send ParsedCommand
creator -> entry_repository -> entry
entry -> entry_repository
entry_repository -> data_store_adapter
data_store_adapter -> entry_repository -> creator -> app


